development: &non_production_settings
  ooyala_api:
    api_key: JkN2w61tDmKgPl4y395Rp1vAdlcq.IqBgb
    api_secret: nU2WjeYoEY0MJKtK1DRpp1c6hNRoHgwpNG76dJkX
    
test:
  <<: *non_production_settings

production:
  <<: *non_production_settings